apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ktor-jvm
  labels:
    app: ktor-jvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktor-jvm
  template:
    metadata:
      labels:
        app: ktor-jvm
    spec:
      containers:
        - name: ktor-jvm
          image: ktor-jvm:v1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080