apiVersion: v1
kind: Service
metadata:
  name: service-ktor-jvm
  labels:
    app: ktor-jvm
spec:
  type: NodePort
  selector:
    app: ktor-jvm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000