apiVersion: v1
kind: Service
metadata:
  name: service-ktor-native
  labels:
    app: ktor-native
spec:
  type: NodePort
  selector:
    app: ktor-native
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001